version: '3.8'

services:
  valkey:
    image: valkey/valkey:8.1.2 # or whichever stable version you want
    container_name: valkey
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - valkey_data:/data

  qdrant:
    image: qdrant/qdrant:v1.14.1 # pin a stable version
    container_name: qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  valkey_data:
  qdrant_data:
